G-FDSL:
  Engine Series: PW4000-94
  Engine Type: PW4462
  Engine Propulsion: JET
  Manufacturer: Boeing
  Family: B737 Classic
  Series: B737-300
  Model: B737-301
  Frame: 737-5
  Frame Qualifier: Altitude_Radio_EFIS
  Precise Positioning: false
  Modifications: []
